# -*- coding: utf-8 -*-
"""CV_A2_Q1_SaliencyMaps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VbMss5Wl6ELByTK0U7qcP5LXDCO1n5t-
"""

import torch
import pandas as pd
import numpy as np
import cv2
import glob

from google.colab.patches import cv2_imshow

list_names = []

for i in range(11, 18):
    if (i != 22 and i != 26 and i != 27):
        list_names.append('16_' + str(i) + "_s.jpg")

list_names = 'NonDLSM_' + name

from google.colab import files

for name in list_names:
    # name =  '15_11_s.jpg'
    image = cv2.imread('/content/' + name)
    saliency = cv2.saliency.StaticSaliencySpectralResidual_create()
    (success, saliencyMap) = saliency.computeSaliency(image)
    saliencyMap = (saliencyMap * 255).astype("uint8")
    cv2_imshow(image)
    cv2_imshow(saliencyMap)
    cv2.imwrite('NonDLSM_' + name, saliencyMap)
    files.download('NonDLSM_' + name)
    # sleep(30)   
    cv2.waitKey(0)